[package]
name = "ether-salvo-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "api", "entity", "migration", "utils"]

[workspace.dependencies]
sea-orm = { version = "1.1.2", features = ["sqlx-postgres", "runtime-tokio-rustls", "debug-print"] }
salvo = { version = "0.74.3", features = ["oapi", "cors"] }
serde = { version = "1.0.216", features = ["derive"] }
tracing = "0.1.41"
redis = "0.27.6"
chrono = "0.4.39"

[dependencies]
api = { path = "api" }
entity = { path = "entity" }
migration = { path = "migration" }
utils = { path = "utils" }
