//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub menu_id: i64,
    pub parent_id: Option<i64>,
    pub name: String,
    pub menu_type: i32,
    pub icon: Option<String>,
    pub path: Option<String>,
    pub sort: i32,
    pub extra: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_menu::Entity")]
    RoleMenu,
}

impl Related<super::role_menu::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleMenu.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
